### ISSUE TITLE
7/4 company 修正依頼

### ISSUE THREAD

**Issue by kanae-chaika** [s-hashizume/company#1]
対象サイト：https://s-hashizume.github.io/company/index.html
元サイト：https://www.edge-intl.co.jp/

前回よりずいぶん良くなりました！

### PC （幅1920px）

- [x] Gナビの子メニューの矢印と文字の太さ・大きさを元サイトに揃える

![スクリーンショット 2023-07-04 10 48 54](https://github.com/s-hashizume/company/assets/84834399/a469028c-3440-41e2-8438-7668ae9190c5)

- [x] Gナビのフォントが2種類混在している。
（what fontでHelveticaとなっているものは、firefoxで見ると実際は游ゴシックが適用されているが、場所によってフォントのfamilyとsizeが違う）

![スクリーンショット 2023-07-04 10 49 41](https://github.com/s-hashizume/company/assets/84834399/4d2b2c88-a3b3-48ad-a104-22613090002d)

![スクリーンショット 2023-07-04 11 23 10](https://github.com/s-hashizume/company/assets/84834399/8e118640-85a6-4611-8d64-71899c9a9136)

![スクリーンショット 2023-07-04 11 23 44](https://github.com/s-hashizume/company/assets/84834399/1ee474a1-995f-4b56-b271-b2700f4ca3da)

- [x] Venture to・・・の文字がGナビの上に来る（重なり順修正）

https://github.com/s-hashizume/company/assets/84834399/e9428ecf-f007-4f79-a3fb-f96e75adb5d7

- [x] Venture to・・・の文字の背景のグレーの位置が違う

![スクリーンショット 2023-07-04 10 56 11](https://github.com/s-hashizume/company/assets/84834399/3c820e05-04d1-4430-b997-e039ec1c0f79)

- [x] スライドを送るボタンの最初の色をグレーにして押せないように修正
![スクリーンショット 2023-07-04 11 00 45](https://github.com/s-hashizume/company/assets/84834399/24c42fe7-1af6-48d2-9023-ded97fee0e9e)

- [x] #4 
元サイトはswiperというjsを使っているので、自動で入れ子構造が複雑になっているが、コピーサイトではswiperを使っていないので、真似しないでください。
不要なdivを省き、一番シンプルなul li aの入れ子構造に変更してください。
また、見えていない不要な項目は削除してください。
その上で、アニメーションが動くようにしてください。

https://github.com/s-hashizume/company/assets/84834399/93ee6254-6d64-4fce-b36e-3bdb439f73ea

- [ ] Feature Case Study も、Mediaと同様なので、一番シンプルな構造にして、見えていない不要な要素は削除してください。 #4 

- [x] リンク文字・矢印のサイズが若干違う

![スクリーンショット 2023-07-04 12 06 19](https://github.com/s-hashizume/company/assets/84834399/151030a3-75d5-4ef4-b998-d5a2ba46d0a6)

![スクリーンショット 2023-07-04 12 06 46](https://github.com/s-hashizume/company/assets/84834399/92bd567c-ac15-4124-bcae-93f2d60f2038)

- [x] .recruit-linkと.inquiry-linkは共通部分が多いですね。
共通で使用するclassをひとつ追加して、cssの重複を無くしてください。
例）共通で使用するclassを.contact-linkとすると、以下のようになります。
```
<a class="contact-link recruit-link" href="#">
・・・
 </a>
```
```
.contact-link {
共通のcss指定
}
```

- [x]  .recruit-linkと.inquiry-linkの文字にtransitionがついていないので、パキッと色が変わります。
transitionをつけましょう。
また、下記の!importantは不要なので削除してください。
```
.contact-recruit a:hover {
    color: #fff !important;
}
```
セレクタも、例えば上の例の`.contact-link`を使用する場合は、`.contact-link:hover `でいいですね。
```
.contact-link {
color: #191919;
transition: 〇〇;
}
.contact-link:hover {
color: #fff;
}
```

- [x] 下記が重複しています。
aをhoverした時に変化すればいいので、`.action-bg:hover`は不要です。
また、こちらも上記の共通classを使用しましょう。
![スクリーンショット 2023-07-04 12 32 51](https://github.com/s-hashizume/company/assets/84834399/41f31698-c0bb-4c33-9f12-9bc948b60f06)

- [x] #3
元サイト

https://github.com/s-hashizume/company/assets/84834399/f6f160f8-78af-4999-81aa-198e43d66030

コピーサイト

https://github.com/s-hashizume/company/assets/84834399/c121f796-a946-4186-8c3d-bc034b546202

- [x] footerメニューも、若干文字サイズが違うのと、Gナビ同様にフォントが混在しています。

![スクリーンショット 2023-07-04 12 38 30](https://github.com/s-hashizume/company/assets/84834399/06d2792b-b164-4400-abed-f21b51344e82)

- [x] 上に戻るボタンのホバー時のデザインが違う

元サイト
![スクリーンショット 2023-07-04 12 43 44](https://github.com/s-hashizume/company/assets/84834399/54dc2352-470f-4574-a608-a2637d6beb15)

コピーサイト
![スクリーンショット 2023-07-04 12 43 54](https://github.com/s-hashizume/company/assets/84834399/eafeccbb-f1b9-4f86-a459-12684608ee03)

ーーーーーー 追記 17:00

- [x] .p-containerの`height: 144px;`はやめましょう。
.p-c-leadを`position: absolute;`にしたために、高さがなくなってheightが必要になったのではないでしょうか？

その場合、absoluteは使用せず、下記のどちらかにして、次のsectionとの余白はmarginかpaddingで取ってください。
```
.p-c-lead {
margin-top: -72px;
}
```

```
.p-c-lead {
position: relative;
top: -72px;
}
```

- [x] PCもスマホもですが、widthのpx指定は基本的にはNGと思ってください。
文字数が変わったり、font-sizeを変更したりする度に、pxを変更することになりますよね？

![スクリーンショット 2023-07-04 16 57 43](https://github.com/s-hashizume/company/assets/84834399/181b553b-abe6-4d02-a075-e769a3152dc3)

この場合、widthを指定しない方法は主に2とおりあります。

簡単な方法
```
.row1 {
display:inline-block;
}
```

元サイトの方法
```
.row1の親要素 {
display: flex;
flex-direction: column;
align-items: flex-start;
}
```

**Comment by kanae-chaika** [comment]
@s-hashizume 
こちらの修正対応をお願いします！

**Comment by kanae-chaika** [comment]
@s-hashizume 
17:00 追記しました

**Comment by kanae-chaika** [comment]
@s-hashizume 

- [x] お問合せの高さが縮んだ時に、headerの薄グレーの下線が見えています。
あと1px下まで伸びるようにして、下線が見えないようにしましょう。
やり方わからなかったら聞いてください。

コピーサイト

![スクリーンショット 2023-07-07 12 21 06](https://github.com/s-hashizume/company/assets/84834399/855b1818-e6e1-4eb1-a1d1-bf197fd7fbad)


元サイト：下線が見えないようになっている

![スクリーンショット 2023-07-07 12 21 24](https://github.com/s-hashizume/company/assets/84834399/1b76b1f4-c528-4698-af0e-f4bcee96894e)

**Comment by kanae-chaika** [comment]
@s-hashizume 

- [x] .contact-link

>.recruit-linkと.inquiry-linkの文字にtransitionがついていないので、パキッと色が変わります。

こちらについてですが、colorとtransitionの指定が多すぎて複雑になっています。

1.  .contact-link 内の文字のcolorとtransitionの指定を全てトル
2. 下記で実装

```
.contact-link {
color: #191919;
transition: 〇〇;
}
.contact-link:hover {
color: #fff;
}
```


- [x] .p-c-lead と .p-c-l__body

>.p-containerのheight: 144px;はやめましょう。

PCはOKです！
top: -72px; をスマホで解除する方法ですが、
position:relative;を重複で上書きしているので削除してください。

①
![スクリーンショット 2023-07-07 13 20 23](https://github.com/s-hashizume/company/assets/84834399/6a6abff1-89ab-4502-981e-b6275298e7b6)

top:auto;ももちろんOKですが、
position: static; のみ入れてtopを自動で効かなくする方法もあります。


また、スマホで .p-c-l__body が position: absolute;になっていますが、これは高さが無くなるので良くないです。
position: absolute;を削除してください。

②
![スクリーンショット 2023-07-07 13 31 45](https://github.com/s-hashizume/company/assets/84834399/41157a45-e773-493f-b4a8-d00b79de47ae)

そうすれば、①の.p-c-lead の padding-bottom: 76.9px; も不要になるので削除してください。

**Comment by kanae-chaika** [comment]
@s-hashizume 
すみません、こちらは今日気づいたので追加です。

- [x]  Our Service のホバー時の赤い丸のアニメーションも元サイトのようにしてください。

https://github.com/s-hashizume/company/assets/84834399/3834b78f-d010-4a14-8bed-17f4d0baabc9

**Comment by kanae-chaika** [comment]
@s-hashizume 
追記

- [x] font-family の重複
.service-container に、bodyと同じフォントが指定されているので削除してください。
元サイトの、意味のないコードをコピーするのはやめましょう。
他の箇所にも重複がないか、font-familyで検索して、不要部分があれば削除してください。

![スクリーンショット 2023-07-07 19 10 04](https://github.com/s-hashizume/company/assets/84834399/4c718650-ce61-4338-813d-5d631256a7c2)

**Comment by s-hashizume** [comment]
@kanae-chaika 
チェック項目が空白の項目を修正させて頂きました！

**Comment by kanae-chaika** [comment]
@s-hashizume 

>Gナビのフォントが2種類混在している。

- [x] ここにまだ不要なフォントが重複して入っています

![スクリーンショット 2023-07-11 23 49 44](https://github.com/s-hashizume/company/assets/84834399/01fd6060-2123-4e7b-b26a-59736be71ad3)


>Venture to・・・の文字の背景のグレーの位置が違う

これは何か変更したでしょうか？


>お問合せの高さが縮んだ時に、headerの薄グレーの下線が見えています。
あと1px下まで伸びるようにして、下線が見えないようにしましょう。
やり方わからなかったら聞いてください。

変わっていないです。違いがわかりますか？

![スクリーンショット 2023-07-11 23 47 15](https://github.com/s-hashizume/company/assets/84834399/2f82bc0b-81c0-4a0e-a797-a1ed85497fcb)


> >.contact-link
> .recruit-linkと.inquiry-linkの文字にtransitionがついていないので、パキッと色が変わります。
> 
> こちらについてですが、colorとtransitionの指定が多すぎて複雑になっています。
> 
> .contact-link 内の文字のcolorとtransitionの指定を全てトル
> 下記で実装

できていないです

.contact-link のtransitionが0.3sなのに、子要素に0.5sが指定されているので、0.5sが適用されています。
不要なtransitionはすべて削除してください。

![スクリーンショット 2023-07-12 0 11 44](https://github.com/s-hashizume/company/assets/84834399/756723c6-359f-4d0a-9458-83f4ff0bace4)
![スクリーンショット 2023-07-12 0 12 00](https://github.com/s-hashizume/company/assets/84834399/8724b87a-e846-4daa-96cb-9b29c1b23342)
![スクリーンショット 2023-07-12 0 12 18](https://github.com/s-hashizume/company/assets/84834399/c009a706-2c20-40a8-925e-afa84a917ae9)


>  また、スマホで .p-c-l__body が position: absolute;になっていますが、これは高さが無くなるので良くないです。
> position: absolute;を削除してください。
> 
> ②
> スクリーンショット 2023-07-07 13 31 45
> 
> そうすれば、①の.p-c-lead の padding-bottom: 76.9px; も不要になるので削除してください。

これができていないです

**Comment by s-hashizume** [comment]
@kanae-chaika 
> Gナビのフォントが2種類混在している。

の修正を致しました！

## 修正点
```
.header-wrapper-nav-list-link {
    font-family: "Yu Gothic", YuGothic, "Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN", "メイリオ", "Meiryo", sans-serif;
    color: #191919;
}
```
のfont-familyの削除

**Comment by s-hashizume** [comment]
@kanae-chaika 
PC版修正完了致しましので、ご確認お願い致します！

>Venture to・・・の文字の背景のグレーの位置が違う
```
.top-contents-wrap::before {
    content: "";
    background: #F0F4F8;
    display: block;
    position: absolute;
    top: auto;
    left: 64px;
    bottom: 13.45vw;
    height: 31.94vw;
    width: 100%;
    z-index: -1;
}
```
上記のように修正

>お問合せの高さが縮んだ時に、headerの薄グレーの下線が見えています。
```
.scrolled .header-wrapper-contact {
    height: calc(100% + 1px);
}
```
divタグ等を元に戻して、上記に修正

>colorとtransitionの指定が多すぎて複雑になっています
```
.contact-title h2 {
    font-family: 'Libre Baskerville', serif;
    font-size: 50px;
    font-weight: 400;
    transition: color 0.5s;
}

.contact-body h3 {
    margin-top: 0;
    font-size: 32px;
    line-height: 48px;
    font-family: "游明朝", YuMincho, "Hiragino Mincho ProN", "Hiragino Mincho Pro", "HG明朝E", "ＭＳ 明朝", serif;
    font-weight: 400;
    transition: color 0.5s;
}

.contact-body p {
    display: block;
    margin-top: 20px;
    font-size: 15px;
    line-height: 27px;
    transition: color 0.5s;
}
```
上記のtransitionを削除

>また、スマホで .p-c-l__body が position: absolute;になっていますが、これは高さが無くなるので良くないです。position: absolute;を削除してください。
```
　　.p-c-lead {
        display: block;
        position: static;
    }

    .p-c-l__body {
        font-size: 20px;
        font-weight: 200;
        margin-top: 38px;
    }
```
上記のように修正

**Comment by kanae-chaika** [comment]
@s-hashizume 
↑ コード書いてくれてすごいわかりやすかったです。
OKです！
