### ISSUE TITLE
7/4 company 修正依頼2

### ISSUE THREAD

**Issue by kanae-chaika** [s-hashizume/company#2]
対象サイト：https://s-hashizume.github.io/company/index.html
元サイト：https://www.edge-intl.co.jp/

### スマホ（幅375px〜414px）

- [x] スマホのbreak pointは (max-width: 1023px)なのでしょうか？これではタブレットの縦もスマホ表示になってしまいます。

- [x] .top-contents-wrap-character:nth-child(1) この.top-contents-wrap-characterは一つしかなので、:nth-child(1)は不要ではないでしょうか？

![スクリーンショット 2023-07-04 16 40 27](https://github.com/s-hashizume/company/assets/84834399/ec7ad09f-afc2-4d64-b014-aae9f6f7beb6)

- [x] PC版に書きましたが、.row1などのwidth指定はやめましょう。

![スクリーンショット 2023-07-04 16 57 43](https://github.com/s-hashizume/company/assets/84834399/72f81c40-0ee7-4ba6-9088-052f9f8c2186)

- [x] 東日本旅客鉄道株式会社などの文字の下の余白がない

![スクリーンショット 2023-07-04 17 24 19](https://github.com/s-hashizume/company/assets/84834399/6fbfedc9-5862-4d51-8eec-d7728485265c)

- [x] リンクの矢印のサイズ・文字のサイズが違います

![スクリーンショット 2023-07-04 17 10 28](https://github.com/s-hashizume/company/assets/84834399/825df23a-d0ae-470c-bafe-4bdeb5e1e2e4)

![スクリーンショット 2023-07-04 17 11 57](https://github.com/s-hashizume/company/assets/84834399/c1e18cf2-29d3-4003-9967-38804f246656)

- [x] 文字サイズが若干違います

![スクリーンショット 2023-07-04 17 11 34](https://github.com/s-hashizume/company/assets/84834399/c46e1dc7-6667-42d7-bdfb-a4642706dbcb)

- [x] recruitとcontactのリンクが違います
- [ ] 
![スクリーンショット 2023-07-04 17 13 45](https://github.com/s-hashizume/company/assets/84834399/a1e06219-4773-420b-910d-245a1e0bb2b4)

- [x] おそらくfont-weightが違うせいで、文字が薄く見えます

![スクリーンショット 2023-07-04 17 15 59](https://github.com/s-hashizume/company/assets/84834399/046be55d-9dc6-41de-9c17-5d5f2c0b7715)

- [x] PCにも書きましたが、font-familyが混在しています

![スクリーンショット 2023-07-04 17 16 19](https://github.com/s-hashizume/company/assets/84834399/8dcfa0fd-dcfc-4e2e-99bd-861a038286bf)

- [x] iphoneXRでOur Service が崩れています

![スクリーンショット 2023-07-04 17 19 18](https://github.com/s-hashizume/company/assets/84834399/dfe0e28d-67b1-416b-99a6-7ad72025d983)

- [x] iphoneXRで2つのバナーが左に寄っています

![スクリーンショット 2023-07-04 17 21 21](https://github.com/s-hashizume/company/assets/84834399/eac824e6-dc7d-4c0a-97ae-9d66fe20d448)

- [x] 自分のスマホ実機で、元サイトとコピーサイトを見比べましたか？？

**Comment by kanae-chaika** [comment]
@s-hashizume 
スマホ版です！
修正お願いします。

**Comment by kanae-chaika** [comment]
- [x] スマホのブレイクポイント
>スマホのbreak pointは (max-width: 1023px)なのでしょうか？これではタブレットの縦もスマホ表示になってしまいます。

ブレイクポイントを414pxにした根拠は何でしょうか？？

iPhone Pro や Max のことを視野に入れましたか？
manaさんの本や、codestepのブレイクポイントは何pxだったでしょうか？→回答ください
お渡ししたsample_siteのブレイクポイントは何pxでしたか？→回答ください

![スクリーンショット 2023-07-07 18 29 12](https://github.com/s-hashizume/company/assets/84834399/1be3f7b8-110f-4b76-84c9-73112980853c)
https://qiita.com/tomohisaota/items/f8857d01f328e34fb551

元サイトのcssを@mediaで検索すると、ブレイクポイントを検索できます。

https://github.com/s-hashizume/company/assets/84834399/df32268b-b68c-4c9d-91d2-97be633feeed
@media screen and (min-width: 1024px) がたくさんでてきますが、これはタブレットとPCのブレイクポイントです。
そして、タブレットとスマホを共通デザインにしている箇所が多いですね。

```
結論を言うと、414pxでの分岐は、iPhone Pro や Max で崩れるのでNGです。
ユアスタのサイトでは iPad mini6に対応するため、744px未満の端末をスマホと定義しています。
それ以外のブレイクポイントであっても、根拠がちゃんとあればいいです。（googleで調べてこういう理由がある等）
また、新しいデバイスが世の中に出てくる度に、常に再検討する必要があります。
```


- [ ] .top-contents-wrap-character
前回、nth-childがあったので気づかなかったのですが、同じセレクタが2回書かれていますので、ひとつにしてください。
1891と1885行目
![スクリーンショット 2023-07-07 18 55 03](https://github.com/s-hashizume/company/assets/84834399/13933823-146e-4058-984e-2a4f611d3754)


ーーーーーーーー

スマホに関して、他はOKです！！

**Comment by s-hashizume** [comment]
@kanae-chaika 
チェック項目が空白の項目を修正させて頂きました！

**Comment by kanae-chaika** [comment]
@s-hashizume 

> .top-contents-wrap-character
前回、nth-childがあったので気づかなかったのですが、同じセレクタが2回書かれていますので、ひとつにしてください。
1891と1885行目

直ってないです

**Comment by s-hashizume** [comment]
@kanae-chaika 
>同じセレクタが2回書かれていますので、ひとつにしてください。

.top-contents-wrap-characterの重複を削除しました!

**Comment by kanae-chaika** [comment]
@s-hashizume 
OKです！
closeします
