### ISSUE TITLE
Mediaの2つ目のホバーアニメーションが効かない←入れ子構造がおかしい

### ISSUE THREAD

**Issue by kanae-chaika** [s-hashizume/company#4]
@s-hashizume 
伝わっていない部分があったので、細かく分解しました。

- [x] 2つめのホバーアニメーション

- [x] .media-slide の不要なcss指定を削除
position: relative; width: 320px; など必要でしょうか？
チェックを外しても変わらないものは不要なのですべて削除してください。

![スクリーンショット 2023-07-07 12 30 58](https://github.com/s-hashizume/company/assets/84834399/5a94ad5a-0059-4b90-96cb-14af22561215)

- [x] .slide-wrapper の不要なcss指定を削除
上記と同様です。

![スクリーンショット 2023-07-07 12 31 24](https://github.com/s-hashizume/company/assets/84834399/e3ff92f2-9703-47da-ad88-1f706a3c6981)

- [x] .slideの不要なcss指定を削除
上記と同様です。

![スクリーンショット 2023-07-07 12 31 54](https://github.com/s-hashizume/company/assets/84834399/dd2871b7-8cb5-47aa-9e5f-cf86ffb320cd)

- [x] 現在表示されているスライドはここまでです
それ以降は見えないので削除
![スクリーンショット 2023-07-07 12 32 17](https://github.com/s-hashizume/company/assets/84834399/ed532877-df62-4cfd-b569-ac8ee5a3c1ce)

- [x] .feature__slide 以下も上記と同様です。

ーーーーーーーー

元サイトからのコピーはやめましょう。
不要なコードが多すぎます。
特に、position や z-index は 本当に必要だと判断した箇所のみに入れるようにしてください。
何度も言いますが、position や z-index を多用すると、サイトの構成が複雑になり予期せぬ挙動が起きるので注意しましょう！

**Comment by s-hashizume** [comment]
@kanae-chaika 
チェック項目が空白の項目を修正させて頂きました！

**Comment by kanae-chaika** [comment]
@s-hashizume 

>.slide-wrapper の不要なcss指定を削除

まだ不要なものがたくさんあります

>.slideの不要なcss指定を削除

同様です

>現在表示されているスライドはここまでです

まだ多くないでしょうか？

>.feature__slide 以下も上記と同様です。

まだこれも多くないですか？


ーーーー

もう一度、
一から自分で考えて自分の力でコーディングすることを考えてください。
不要な要素、知らないのに書いているコードがあるように思います。

![スクリーンショット 2023-07-12 0 02 05](https://github.com/s-hashizume/company/assets/84834399/023dfd02-75df-44fa-bf67-640a2208dcd5)

ここだけインラインでcssを書いてる理由は何ですか？

**Comment by s-hashizume** [comment]
@kanae-chaika 
MediaとFeatureの不必要なcssと表示しなくて良いslideを削除いたしましたので確認のほどよろしくお願い致します！

**Comment by kanae-chaika** [comment]
@s-hashizume 

はい！かなりスッキリしましたね！！！

> - [ ] 現在表示されているスライドはここまでです
> それ以降は見えないので削除
> ![スクリーンショット 2023-07-07 12 32 17](https://github.com/s-hashizume/company/assets/84834399/ed532877-df62-4cfd-b569-ac8ee5a3c1ce)

Mediaはスライド5個目までは必要ですね

- [x] スマホで、まだ不要なcssが残っています。
MediaとFeatureのスマホの指定も、いったん空にして、やり直してください。

- [x] スマホで.slideの指定がめちゃ重複してるので整理してください。

![スクリーンショット 2023-07-12 17 20 31](https://github.com/s-hashizume/company/assets/84834399/e28cb4e7-2598-43a1-adcf-186f4c8dc6d4)

**Comment by s-hashizume** [comment]
@kanae-chaika 
ありがとうございます！
slideの数
スマホ版の再構築
スマホ版の指定を整理
を実施します！

**Comment by s-hashizume** [comment]
@kanae-chaika 
下記が完了致しましたので、ご確認の程よろしくお願い致します！

- Mediaのスライドを５個にする
- スマホ版のMediaとFeatureを再度指定
- 重複していた指定を削除

**Comment by kanae-chaika** [comment]
@s-hashizume 
かなりシンプルになってきました！

- [x] width: 163px; はここではなく、.slideに指定するのが自然だと思います。

![スクリーンショット 2023-07-12 20 06 30](https://github.com/s-hashizume/company/assets/84834399/ebe2e8dd-7b01-4009-a3ff-047c7be8bc76)

- [x] スマホでMediaをタップしたら、赤い線が出ます。

デベロッパー

https://github.com/s-hashizume/company/assets/84834399/333ada6d-3be0-44a7-b952-c88c6b58a774



私のiPhoneではpurposeの上に出ます。

https://github.com/s-hashizume/company/assets/84834399/8246323c-4965-4a9c-8fec-8d8bfc3f0b73

**Comment by s-hashizume** [comment]
@kanae-chaika 
ありがとうございます！
PCでも同箇所を確認したところ、おかしな位置から赤線が出現するようになってしまいましたので、合わせて修正いたします！

**Comment by s-hashizume** [comment]
@kanae-chaika 
下記の修正が完了致しましたのでご確認の程よろしくお願い致します！

- "media-slide"に指定していたwidthを"slide"に変更
- Mediaをホバー及びタップしたら赤のアンダーラインを所定の位置に出現させる

**Comment by kanae-chaika** [comment]
@s-hashizume 
間違いではないんですが、現状ではli.slideをホバーした時に文字色やボーダーのスタイルが変更するようになっていますね。
通常はa:hoverでスタイルを変更するので、そうしてもらってもいいでしょうか？
relativeもaタグにつける方がわかりやすいですね。

![スクリーンショット 2023-07-13 14 57 28](https://github.com/s-hashizume/company/assets/84834399/21fd9f0c-cfdc-4f4f-b734-0c8bb8ddfe02)

![スクリーンショット 2023-07-13 14 59 48](https://github.com/s-hashizume/company/assets/84834399/0bc1fdaa-b5b9-4d56-9ecc-dfb3dfd5ac11)

**Comment by s-hashizume** [comment]
@kanae-chaika 
承知致しました！

**Comment by s-hashizume** [comment]
@kanae-chaika 

```
.slide:hover .c-card-blog__link::after  {
  transform: scaleX(1);
}

.slide:hover .c-card-blog__title {
  color: #C80D2F;
}
```
上記を
```
.c-card-blog__link:hover::after {
    transform: scaleX(1);
}

.c-card-blog__link:hover .c-card-blog__title {
    color: #C80D2F;
}
```
に修正し、".c-card-blog__link"を```position: relative;```にしました！

**Comment by kanae-chaika** [comment]
@s-hashizume 
OKです！！
お疲れ様でした！
